//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteConsole.Cotacao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", ConfigurationName="Cotacao.FachadaWSSGS")]
    public interface FachadaWSSGS {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) of message getValoresSeriesVORequest does not match the default value (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TesteConsole.Cotacao.getValoresSeriesVOResponse getValoresSeriesVO(TesteConsole.Cotacao.getValoresSeriesVORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getValoresSeriesVOResponse> getValoresSeriesVOAsync(TesteConsole.Cotacao.getValoresSeriesVORequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) of message getUltimosValoresSerieVORequest does not match the default value (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TesteConsole.Cotacao.getUltimosValoresSerieVOResponse getUltimosValoresSerieVO(TesteConsole.Cotacao.getUltimosValoresSerieVORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getUltimosValoresSerieVOResponse> getUltimosValoresSerieVOAsync(TesteConsole.Cotacao.getUltimosValoresSerieVORequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) of message getValoresSeriesXMLRequest does not match the default value (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TesteConsole.Cotacao.getValoresSeriesXMLResponse getValoresSeriesXML(TesteConsole.Cotacao.getValoresSeriesXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getValoresSeriesXMLResponse> getValoresSeriesXMLAsync(TesteConsole.Cotacao.getValoresSeriesXMLRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) of message getUltimoValorVORequest does not match the default value (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TesteConsole.Cotacao.getUltimoValorVOResponse getUltimoValorVO(TesteConsole.Cotacao.getUltimoValorVORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getUltimoValorVOResponse> getUltimoValorVOAsync(TesteConsole.Cotacao.getUltimoValorVORequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) of message getUltimoValorXMLRequest does not match the default value (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TesteConsole.Cotacao.getUltimoValorXMLResponse getUltimoValorXML(TesteConsole.Cotacao.getUltimoValorXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getUltimoValorXMLResponse> getUltimoValorXMLAsync(TesteConsole.Cotacao.getUltimoValorXMLRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) of message getValorRequest does not match the default value (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TesteConsole.Cotacao.getValorResponse getValor(TesteConsole.Cotacao.getValorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getValorResponse> getValorAsync(TesteConsole.Cotacao.getValorRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br) of message getValorEspecialRequest does not match the default value (https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TesteConsole.Cotacao.getValorEspecialResponse getValorEspecial(TesteConsole.Cotacao.getValorEspecialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getValorEspecialResponse> getValorEspecialAsync(TesteConsole.Cotacao.getValorEspecialRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://comum.ws.casosdeuso.sgs.pec.bcb.gov.br")]
    public partial class WSSerieVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anoFimField;
        
        private int anoInicioField;
        
        private string avisoField;
        
        private int diaFimField;
        
        private int diaInicioField;
        
        private bool especialField;
        
        private string fonteField;
        
        private string fullNameField;
        
        private string gestorProprietarioField;
        
        private int mesFimField;
        
        private int mesInicioField;
        
        private string nomeAbreviadoField;
        
        private string nomeCompletoField;
        
        private long oidField;
        
        private string periodicidadeField;
        
        private string periodicidadeSiglaField;
        
        private bool possuiBloqueiosField;
        
        private bool publicaField;
        
        private string shortNameField;
        
        private WSValorSerieVO ultimoValorField;
        
        private string unidadePadraoField;
        
        private string unidadePadraoInglesField;
        
        private bool valorDiaNaoUtilField;
        
        private WSValorSerieVO[] valoresField;
        
        /// <remarks/>
        public int anoFim {
            get {
                return this.anoFimField;
            }
            set {
                this.anoFimField = value;
                this.RaisePropertyChanged("anoFim");
            }
        }
        
        /// <remarks/>
        public int anoInicio {
            get {
                return this.anoInicioField;
            }
            set {
                this.anoInicioField = value;
                this.RaisePropertyChanged("anoInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string aviso {
            get {
                return this.avisoField;
            }
            set {
                this.avisoField = value;
                this.RaisePropertyChanged("aviso");
            }
        }
        
        /// <remarks/>
        public int diaFim {
            get {
                return this.diaFimField;
            }
            set {
                this.diaFimField = value;
                this.RaisePropertyChanged("diaFim");
            }
        }
        
        /// <remarks/>
        public int diaInicio {
            get {
                return this.diaInicioField;
            }
            set {
                this.diaInicioField = value;
                this.RaisePropertyChanged("diaInicio");
            }
        }
        
        /// <remarks/>
        public bool especial {
            get {
                return this.especialField;
            }
            set {
                this.especialField = value;
                this.RaisePropertyChanged("especial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fonte {
            get {
                return this.fonteField;
            }
            set {
                this.fonteField = value;
                this.RaisePropertyChanged("fonte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("fullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string gestorProprietario {
            get {
                return this.gestorProprietarioField;
            }
            set {
                this.gestorProprietarioField = value;
                this.RaisePropertyChanged("gestorProprietario");
            }
        }
        
        /// <remarks/>
        public int mesFim {
            get {
                return this.mesFimField;
            }
            set {
                this.mesFimField = value;
                this.RaisePropertyChanged("mesFim");
            }
        }
        
        /// <remarks/>
        public int mesInicio {
            get {
                return this.mesInicioField;
            }
            set {
                this.mesInicioField = value;
                this.RaisePropertyChanged("mesInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeAbreviado {
            get {
                return this.nomeAbreviadoField;
            }
            set {
                this.nomeAbreviadoField = value;
                this.RaisePropertyChanged("nomeAbreviado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeCompleto {
            get {
                return this.nomeCompletoField;
            }
            set {
                this.nomeCompletoField = value;
                this.RaisePropertyChanged("nomeCompleto");
            }
        }
        
        /// <remarks/>
        public long oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
                this.RaisePropertyChanged("oid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string periodicidade {
            get {
                return this.periodicidadeField;
            }
            set {
                this.periodicidadeField = value;
                this.RaisePropertyChanged("periodicidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string periodicidadeSigla {
            get {
                return this.periodicidadeSiglaField;
            }
            set {
                this.periodicidadeSiglaField = value;
                this.RaisePropertyChanged("periodicidadeSigla");
            }
        }
        
        /// <remarks/>
        public bool possuiBloqueios {
            get {
                return this.possuiBloqueiosField;
            }
            set {
                this.possuiBloqueiosField = value;
                this.RaisePropertyChanged("possuiBloqueios");
            }
        }
        
        /// <remarks/>
        public bool publica {
            get {
                return this.publicaField;
            }
            set {
                this.publicaField = value;
                this.RaisePropertyChanged("publica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string shortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("shortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public WSValorSerieVO ultimoValor {
            get {
                return this.ultimoValorField;
            }
            set {
                this.ultimoValorField = value;
                this.RaisePropertyChanged("ultimoValor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string unidadePadrao {
            get {
                return this.unidadePadraoField;
            }
            set {
                this.unidadePadraoField = value;
                this.RaisePropertyChanged("unidadePadrao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string unidadePadraoIngles {
            get {
                return this.unidadePadraoInglesField;
            }
            set {
                this.unidadePadraoInglesField = value;
                this.RaisePropertyChanged("unidadePadraoIngles");
            }
        }
        
        /// <remarks/>
        public bool valorDiaNaoUtil {
            get {
                return this.valorDiaNaoUtilField;
            }
            set {
                this.valorDiaNaoUtilField = value;
                this.RaisePropertyChanged("valorDiaNaoUtil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public WSValorSerieVO[] valores {
            get {
                return this.valoresField;
            }
            set {
                this.valoresField = value;
                this.RaisePropertyChanged("valores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://comum.ws.casosdeuso.sgs.pec.bcb.gov.br")]
    public partial class WSValorSerieVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anoField;
        
        private int anoFimField;
        
        private bool bloqueadoField;
        
        private bool bloqueioLiberadoField;
        
        private int diaField;
        
        private int diaFimField;
        
        private int mesField;
        
        private int mesFimField;
        
        private long oidField;
        
        private long oidSerieField;
        
        private string svalorField;
        
        private System.Nullable<decimal> valorField;
        
        /// <remarks/>
        public int ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
                this.RaisePropertyChanged("ano");
            }
        }
        
        /// <remarks/>
        public int anoFim {
            get {
                return this.anoFimField;
            }
            set {
                this.anoFimField = value;
                this.RaisePropertyChanged("anoFim");
            }
        }
        
        /// <remarks/>
        public bool bloqueado {
            get {
                return this.bloqueadoField;
            }
            set {
                this.bloqueadoField = value;
                this.RaisePropertyChanged("bloqueado");
            }
        }
        
        /// <remarks/>
        public bool bloqueioLiberado {
            get {
                return this.bloqueioLiberadoField;
            }
            set {
                this.bloqueioLiberadoField = value;
                this.RaisePropertyChanged("bloqueioLiberado");
            }
        }
        
        /// <remarks/>
        public int dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
                this.RaisePropertyChanged("dia");
            }
        }
        
        /// <remarks/>
        public int diaFim {
            get {
                return this.diaFimField;
            }
            set {
                this.diaFimField = value;
                this.RaisePropertyChanged("diaFim");
            }
        }
        
        /// <remarks/>
        public int mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
                this.RaisePropertyChanged("mes");
            }
        }
        
        /// <remarks/>
        public int mesFim {
            get {
                return this.mesFimField;
            }
            set {
                this.mesFimField = value;
                this.RaisePropertyChanged("mesFim");
            }
        }
        
        /// <remarks/>
        public long oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
                this.RaisePropertyChanged("oid");
            }
        }
        
        /// <remarks/>
        public long oidSerie {
            get {
                return this.oidSerieField;
            }
            set {
                this.oidSerieField = value;
                this.RaisePropertyChanged("oidSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string svalor {
            get {
                return this.svalorField;
            }
            set {
                this.svalorField = value;
                this.RaisePropertyChanged("svalor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValoresSeriesVO", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getValoresSeriesVORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long[] in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string in2;
        
        public getValoresSeriesVORequest() {
        }
        
        public getValoresSeriesVORequest(long[] in0, string in1, string in2) {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValoresSeriesVOResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getValoresSeriesVOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TesteConsole.Cotacao.WSSerieVO[] getValoresSeriesVOReturn;
        
        public getValoresSeriesVOResponse() {
        }
        
        public getValoresSeriesVOResponse(TesteConsole.Cotacao.WSSerieVO[] getValoresSeriesVOReturn) {
            this.getValoresSeriesVOReturn = getValoresSeriesVOReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUltimosValoresSerieVO", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getUltimosValoresSerieVORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public long in1;
        
        public getUltimosValoresSerieVORequest() {
        }
        
        public getUltimosValoresSerieVORequest(long in0, long in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUltimosValoresSerieVOResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getUltimosValoresSerieVOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TesteConsole.Cotacao.WSSerieVO getUltimosValoresSerieVOReturn;
        
        public getUltimosValoresSerieVOResponse() {
        }
        
        public getUltimosValoresSerieVOResponse(TesteConsole.Cotacao.WSSerieVO getUltimosValoresSerieVOReturn) {
            this.getUltimosValoresSerieVOReturn = getUltimosValoresSerieVOReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValoresSeriesXML", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getValoresSeriesXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long[] in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string in2;
        
        public getValoresSeriesXMLRequest() {
        }
        
        public getValoresSeriesXMLRequest(long[] in0, string in1, string in2) {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValoresSeriesXMLResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getValoresSeriesXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getValoresSeriesXMLReturn;
        
        public getValoresSeriesXMLResponse() {
        }
        
        public getValoresSeriesXMLResponse(string getValoresSeriesXMLReturn) {
            this.getValoresSeriesXMLReturn = getValoresSeriesXMLReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUltimoValorVO", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getUltimoValorVORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long in0;
        
        public getUltimoValorVORequest() {
        }
        
        public getUltimoValorVORequest(long in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUltimoValorVOResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getUltimoValorVOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TesteConsole.Cotacao.WSSerieVO getUltimoValorVOReturn;
        
        public getUltimoValorVOResponse() {
        }
        
        public getUltimoValorVOResponse(TesteConsole.Cotacao.WSSerieVO getUltimoValorVOReturn) {
            this.getUltimoValorVOReturn = getUltimoValorVOReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUltimoValorXML", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getUltimoValorXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long in0;
        
        public getUltimoValorXMLRequest() {
        }
        
        public getUltimoValorXMLRequest(long in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUltimoValorXMLResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getUltimoValorXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getUltimoValorXMLReturn;
        
        public getUltimoValorXMLResponse() {
        }
        
        public getUltimoValorXMLResponse(string getUltimoValorXMLReturn) {
            this.getUltimoValorXMLReturn = getUltimoValorXMLReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValor", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getValorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string in1;
        
        public getValorRequest() {
        }
        
        public getValorRequest(long in0, string in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValorResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getValorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public decimal getValorReturn;
        
        public getValorResponse() {
        }
        
        public getValorResponse(decimal getValorReturn) {
            this.getValorReturn = getValorReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValorEspecial", WrapperNamespace="http://publico.ws.casosdeuso.sgs.pec.bcb.gov.br", IsWrapped=true)]
    public partial class getValorEspecialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string in2;
        
        public getValorEspecialRequest() {
        }
        
        public getValorEspecialRequest(long in0, string in1, string in2) {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValorEspecialResponse", WrapperNamespace="https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS", IsWrapped=true)]
    public partial class getValorEspecialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public decimal getValorEspecialReturn;
        
        public getValorEspecialResponse() {
        }
        
        public getValorEspecialResponse(decimal getValorEspecialReturn) {
            this.getValorEspecialReturn = getValorEspecialReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FachadaWSSGSChannel : TesteConsole.Cotacao.FachadaWSSGS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FachadaWSSGSClient : System.ServiceModel.ClientBase<TesteConsole.Cotacao.FachadaWSSGS>, TesteConsole.Cotacao.FachadaWSSGS {
        
        public FachadaWSSGSClient() {
        }
        
        public FachadaWSSGSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FachadaWSSGSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FachadaWSSGSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FachadaWSSGSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteConsole.Cotacao.getValoresSeriesVOResponse TesteConsole.Cotacao.FachadaWSSGS.getValoresSeriesVO(TesteConsole.Cotacao.getValoresSeriesVORequest request) {
            return base.Channel.getValoresSeriesVO(request);
        }
        
        public TesteConsole.Cotacao.WSSerieVO[] getValoresSeriesVO(long[] in0, string in1, string in2) {
            TesteConsole.Cotacao.getValoresSeriesVORequest inValue = new TesteConsole.Cotacao.getValoresSeriesVORequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            TesteConsole.Cotacao.getValoresSeriesVOResponse retVal = ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getValoresSeriesVO(inValue);
            return retVal.getValoresSeriesVOReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getValoresSeriesVOResponse> TesteConsole.Cotacao.FachadaWSSGS.getValoresSeriesVOAsync(TesteConsole.Cotacao.getValoresSeriesVORequest request) {
            return base.Channel.getValoresSeriesVOAsync(request);
        }
        
        public System.Threading.Tasks.Task<TesteConsole.Cotacao.getValoresSeriesVOResponse> getValoresSeriesVOAsync(long[] in0, string in1, string in2) {
            TesteConsole.Cotacao.getValoresSeriesVORequest inValue = new TesteConsole.Cotacao.getValoresSeriesVORequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            return ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getValoresSeriesVOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteConsole.Cotacao.getUltimosValoresSerieVOResponse TesteConsole.Cotacao.FachadaWSSGS.getUltimosValoresSerieVO(TesteConsole.Cotacao.getUltimosValoresSerieVORequest request) {
            return base.Channel.getUltimosValoresSerieVO(request);
        }
        
        public TesteConsole.Cotacao.WSSerieVO getUltimosValoresSerieVO(long in0, long in1) {
            TesteConsole.Cotacao.getUltimosValoresSerieVORequest inValue = new TesteConsole.Cotacao.getUltimosValoresSerieVORequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            TesteConsole.Cotacao.getUltimosValoresSerieVOResponse retVal = ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getUltimosValoresSerieVO(inValue);
            return retVal.getUltimosValoresSerieVOReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getUltimosValoresSerieVOResponse> TesteConsole.Cotacao.FachadaWSSGS.getUltimosValoresSerieVOAsync(TesteConsole.Cotacao.getUltimosValoresSerieVORequest request) {
            return base.Channel.getUltimosValoresSerieVOAsync(request);
        }
        
        public System.Threading.Tasks.Task<TesteConsole.Cotacao.getUltimosValoresSerieVOResponse> getUltimosValoresSerieVOAsync(long in0, long in1) {
            TesteConsole.Cotacao.getUltimosValoresSerieVORequest inValue = new TesteConsole.Cotacao.getUltimosValoresSerieVORequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            return ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getUltimosValoresSerieVOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteConsole.Cotacao.getValoresSeriesXMLResponse TesteConsole.Cotacao.FachadaWSSGS.getValoresSeriesXML(TesteConsole.Cotacao.getValoresSeriesXMLRequest request) {
            return base.Channel.getValoresSeriesXML(request);
        }
        
        public string getValoresSeriesXML(long[] in0, string in1, string in2) {
            TesteConsole.Cotacao.getValoresSeriesXMLRequest inValue = new TesteConsole.Cotacao.getValoresSeriesXMLRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            TesteConsole.Cotacao.getValoresSeriesXMLResponse retVal = ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getValoresSeriesXML(inValue);
            return retVal.getValoresSeriesXMLReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getValoresSeriesXMLResponse> TesteConsole.Cotacao.FachadaWSSGS.getValoresSeriesXMLAsync(TesteConsole.Cotacao.getValoresSeriesXMLRequest request) {
            return base.Channel.getValoresSeriesXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<TesteConsole.Cotacao.getValoresSeriesXMLResponse> getValoresSeriesXMLAsync(long[] in0, string in1, string in2) {
            TesteConsole.Cotacao.getValoresSeriesXMLRequest inValue = new TesteConsole.Cotacao.getValoresSeriesXMLRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            return ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getValoresSeriesXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteConsole.Cotacao.getUltimoValorVOResponse TesteConsole.Cotacao.FachadaWSSGS.getUltimoValorVO(TesteConsole.Cotacao.getUltimoValorVORequest request) {
            return base.Channel.getUltimoValorVO(request);
        }
        
        public TesteConsole.Cotacao.WSSerieVO getUltimoValorVO(long in0) {
            TesteConsole.Cotacao.getUltimoValorVORequest inValue = new TesteConsole.Cotacao.getUltimoValorVORequest();
            inValue.in0 = in0;
            TesteConsole.Cotacao.getUltimoValorVOResponse retVal = ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getUltimoValorVO(inValue);
            return retVal.getUltimoValorVOReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getUltimoValorVOResponse> TesteConsole.Cotacao.FachadaWSSGS.getUltimoValorVOAsync(TesteConsole.Cotacao.getUltimoValorVORequest request) {
            return base.Channel.getUltimoValorVOAsync(request);
        }
        
        public System.Threading.Tasks.Task<TesteConsole.Cotacao.getUltimoValorVOResponse> getUltimoValorVOAsync(long in0) {
            TesteConsole.Cotacao.getUltimoValorVORequest inValue = new TesteConsole.Cotacao.getUltimoValorVORequest();
            inValue.in0 = in0;
            return ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getUltimoValorVOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteConsole.Cotacao.getUltimoValorXMLResponse TesteConsole.Cotacao.FachadaWSSGS.getUltimoValorXML(TesteConsole.Cotacao.getUltimoValorXMLRequest request) {
            return base.Channel.getUltimoValorXML(request);
        }
        
        public string getUltimoValorXML(long in0) {
            TesteConsole.Cotacao.getUltimoValorXMLRequest inValue = new TesteConsole.Cotacao.getUltimoValorXMLRequest();
            inValue.in0 = in0;
            TesteConsole.Cotacao.getUltimoValorXMLResponse retVal = ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getUltimoValorXML(inValue);
            return retVal.getUltimoValorXMLReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getUltimoValorXMLResponse> TesteConsole.Cotacao.FachadaWSSGS.getUltimoValorXMLAsync(TesteConsole.Cotacao.getUltimoValorXMLRequest request) {
            return base.Channel.getUltimoValorXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<TesteConsole.Cotacao.getUltimoValorXMLResponse> getUltimoValorXMLAsync(long in0) {
            TesteConsole.Cotacao.getUltimoValorXMLRequest inValue = new TesteConsole.Cotacao.getUltimoValorXMLRequest();
            inValue.in0 = in0;
            return ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getUltimoValorXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteConsole.Cotacao.getValorResponse TesteConsole.Cotacao.FachadaWSSGS.getValor(TesteConsole.Cotacao.getValorRequest request) {
            return base.Channel.getValor(request);
        }
        
        public decimal getValor(long in0, string in1) {
            TesteConsole.Cotacao.getValorRequest inValue = new TesteConsole.Cotacao.getValorRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            TesteConsole.Cotacao.getValorResponse retVal = ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getValor(inValue);
            return retVal.getValorReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getValorResponse> TesteConsole.Cotacao.FachadaWSSGS.getValorAsync(TesteConsole.Cotacao.getValorRequest request) {
            return base.Channel.getValorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TesteConsole.Cotacao.getValorResponse> getValorAsync(long in0, string in1) {
            TesteConsole.Cotacao.getValorRequest inValue = new TesteConsole.Cotacao.getValorRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            return ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getValorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteConsole.Cotacao.getValorEspecialResponse TesteConsole.Cotacao.FachadaWSSGS.getValorEspecial(TesteConsole.Cotacao.getValorEspecialRequest request) {
            return base.Channel.getValorEspecial(request);
        }
        
        public decimal getValorEspecial(long in0, string in1, string in2) {
            TesteConsole.Cotacao.getValorEspecialRequest inValue = new TesteConsole.Cotacao.getValorEspecialRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            TesteConsole.Cotacao.getValorEspecialResponse retVal = ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getValorEspecial(inValue);
            return retVal.getValorEspecialReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TesteConsole.Cotacao.getValorEspecialResponse> TesteConsole.Cotacao.FachadaWSSGS.getValorEspecialAsync(TesteConsole.Cotacao.getValorEspecialRequest request) {
            return base.Channel.getValorEspecialAsync(request);
        }
        
        public System.Threading.Tasks.Task<TesteConsole.Cotacao.getValorEspecialResponse> getValorEspecialAsync(long in0, string in1, string in2) {
            TesteConsole.Cotacao.getValorEspecialRequest inValue = new TesteConsole.Cotacao.getValorEspecialRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            return ((TesteConsole.Cotacao.FachadaWSSGS)(this)).getValorEspecialAsync(inValue);
        }
    }
}
